- name: Adding user to master server
  local_action: shell useradd  "{{ user_name }}" && echo "{{ user_name }}":user5678 | chpasswd
  tags:
   - grant

- name: Generating Keys for user
  become: True
  become_user: "{{ user_name }}"
  become_ask_pass : True
  local_action: shell mkdir -p /tmp/{{ user_name }}/ && whoami && ssh-keygen  -C {{ user_name }} -f /tmp/{{ user_name }}/id_rsa -N ""
  tags:
    - grant

